name: PrintStat
main: com.printstat.ServerStatPlugin
version: 0.7
api-version: 1.13
commands:
  print:
    description: 서버 정보를 출력하는 플러그인
    usage: |
    
      /print memory - 현재 서버 메모리 사용량을 출력합니다.
      /print tps - 현재 서버의 tps를 출력합니다.
      /print info - 현재 서버의 정보를 출력합니다.


